2022-04-08 09:10:10,809 (__init__.py:490 MainThread) INFO - TeleBot: "Started polling."
unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "bot.py", line 568, in <module>
    bot.polling()
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/__init__.py", line 485, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout)
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/__init__.py", line 544, in __threaded_polling
    raise e
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/__init__.py", line 506, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/util.py", line 87, in raise_exceptions
    raise self.exception_info
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/__init__.py", line 323, in __retrieve_updates
    self.process_new_updates(updates)
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/__init__.py", line 396, in process_new_updates
    self.process_new_callback_query(new_callback_queries)
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/__init__.py", line 428, in process_new_callback_query
    self._notify_command_handlers(self.callback_query_handlers, new_callback_querys)
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/__init__.py", line 2183, in _notify_command_handlers
    if self._test_message_handler(message_handler, message):
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/__init__.py", line 2149, in _test_message_handler
    if not self._test_filter(message_filter, filter_value, message):
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/__init__.py", line 2170, in _test_filter
    return test_cases.get(message_filter, lambda msg: False)(message)
  File "/home/easyrights/Documents/easyRights_bot/env/lib/python3.8/site-packages/telebot/__init__.py", line 2167, in <lambda>
    'func': lambda msg: filter_value(msg)
  File "bot.py", line 296, in <lambda>
    @bot.callback_query_handler(lambda query: query.data in SERVICES[retrieve_user(query.from_user.id)['selected_pilot']])
KeyError: 'Birmingham'
